title:            Duct Tape and Turing Machines
tagline:
description:      Duct Tape and Turing Machines
#Comment out url when working locally to resolve base urls correctly
#url:              https://thegreata.pe
logo: "birds.jpg"

# Owner/author information
owner:
  name:           Thomas Mayfield
  avatar:         bio-photo.png
  bio:            "Polyglot programmer who loves the weird beautiful chaos of humans building software together. Fitness nerd. Southern kid living in Massachusetts."
  email:          Thomas.Mayfield@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: thegreatape
  facebook:
  github: thegreatape
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Open Source
    url: /open-source

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
markdown:    kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      category: "articles"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: pretty

syntax_highlighter_opts:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: rouge

plugins:
  - jekyll-redirect-from

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
